### PR TITLE
Mapview

### PR DESCRIPTION
**Pull request by TaiNguyen2407**
MapView + UserLocation. There will be conflicts for sure since we are working cross files.

### CODE REVIEW

**Comment by anwar-ulhaq** [comment]
I had made some changes to conflicting project.pbxproj file which will change directory structure e.g. Giao created a Folder View Model where as Tai created ViewModel. All this kind of inconsistencies are fixed for a while. Entry point of app has tobe discussed which means that with this merge Gioa's AudioRecording screen would be visible not the Map, so we need to figure out how Tai's Home() view and Gioa's AudioRecording() could be combined into one starting point of App.

**Comment by giaongo** [comment]
Hi @anwar-ulhaq and @TaiNguyen2407 , thanks a lot for the work, I have already figured out how to combine MapView and AudioRecordingView in my PR while building the sliding bar and voice wave. So technically, I have created a layout for ContentView, considered as a main app view, that contains the MapView and BottomBarView. Once user clicks the audio button, the SlidingModalView shows up with the content of AudioRecordingView. All designs I did so far follow up with the latest app look on Figma. 

🫡😀

**Review by giaongo — COMMENTED** [review]
Finished Review

**Review by giaongo — APPROVED** [review]
Approval on PR

**Pull request merged**
